kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo1
  namespace: workshop
  labels:
    app: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
        - name: cotd
          image: docker.io/emverdes/cotd:1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NAME
              value: cotd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
